import os
import shutil
import dash
from dash import html
import niceview.utils.io as vio
from niceview.interface.interface import visualization_img_input


def reset(n_clicks, spot_cell_option, visual_type, folder_id, work_dir):
    """Refresh the base histology viewer for the current spatial omics session."""
    changed_id = [p['prop_id'] for p in dash.callback_context.triggered][0]
    if 'n_clicks' not in changed_id:
        raise dash.exceptions.PreventUpdate

    map_input = visualization_img_input(folder_id, work_dir, geojson_coords=None)
    return html.Div(id="input-image", children=[map_input])


def save_roi(rois, folder_id, work_dir):
    """Save coordinates.

    Args:
        rois (list): List of ROIs from VivViewer.

    Returns:
        json file.
    """
    if rois is not None and len(rois) > 0:

        coords = []
        for roi in rois:
            points = roi.get("points", [])
            if not points: continue

            if roi.get("type") == "rect" or roi.get("type") == "polygon":
                # The frontend sends an array of points. It could be 2 points (min/max)
                # or 4+ points for a full polygon/rect. To be safe, extract min and max
                # from ALL points if it's explicitly a rect, or just close the polygon.
                poly = [p for p in points if p]  # Ensure no nulls
                if poly and poly[0] != poly[-1]:
                    poly.append(poly[0])
                coords.append(poly)

        # Save verbatim rois as roi.json just in case
        roi_name = f'{work_dir}/user{folder_id}/roi.json'
        vio.dump_json(rois, roi_name, indent=2)

        coordjson_name = f'{work_dir}/user{folder_id}/coords.json'
        vio.dump_json(coords, coordjson_name, indent=2)
    else:
        # Clear them out if no ROIs
        roi_name = f'{work_dir}/user{folder_id}/roi.json'
        coordjson_name = f'{work_dir}/user{folder_id}/coords.json'
        if vio.exists(roi_name): vio.remove(roi_name)
        if vio.exists(coordjson_name): vio.remove(coordjson_name)

    return None


def _safe_delete_session_path(path, label):
    """Delete one generated session path without failing the whole cleanup."""
    if not path:
        return
    try:
        if os.path.isdir(path):
            shutil.rmtree(path)
            print(f"Deleted {label}: {path}")
        elif os.path.isfile(path):
            os.remove(path)
            print(f"Deleted {label}: {path}")
    except Exception as e:
        print(f"Failed to delete {label} ({path}): {e}")


def clear_cache_forcall(*args):
    if len(args) >= 4:
        n_clicks, folder_id, work_dir = args[:3]
        if not n_clicks:
            return None
    elif len(args) >= 2:
        folder_id, work_dir = args[:2]
    else:
        raise TypeError("clear_cache_forcall requires folder_id and work_dir")

    session_id = str(folder_id or "")
    project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    chat_dir = os.environ.get("LOKI_CHAT_DIR", os.path.join(project_root, "chat_sessions"))
    tmp_base = os.environ.get("LOKI_TMP_BASE", os.path.join(project_root, "tmp_data"))

    # Delete everything generated by this browser session:
    # uploaded image/h5ad files, converted viewer cache, ROI state, and chat artifacts.
    if session_id:
        _safe_delete_session_path(os.path.join(chat_dir, session_id), "chat session data")
        _safe_delete_session_path(os.path.join(tmp_base, "ome_tiff_cache", session_id), "OME-TIFF conversion cache")
        _safe_delete_session_path(os.path.join(tmp_base, "uploads", session_id), "temporary uploads")
    else:
        print("Skipping session-specific cleanup because session id is empty.")

    if work_dir and vio.exists(work_dir):
        try:
            vio.rmdir(work_dir)
            print(f"Deleted work directory and uploaded data: {work_dir}")
        except Exception as e:
            print(f"Failed to delete work directory ({work_dir}): {e}")

    # (S3 / EC2 cleanup removed — local-only mode)

    print("Stopping server...")
    os._exit(0)
    return None
